// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_info.proto
#ifndef GRPC_user_5finfo_2eproto__INCLUDED
#define GRPC_user_5finfo_2eproto__INCLUDED

#include "user_info.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace userinfo {

class UserAction final {
 public:
  static constexpr char const* service_full_name() {
    return "userinfo.UserAction";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Login(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::userinfo::LoginResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::LoginResponse>> AsyncLogin(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::LoginResponse>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::LoginResponse>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::LoginResponse>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    virtual ::grpc::Status Register(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::userinfo::RegisterResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::RegisterResponse>> AsyncRegister(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::RegisterResponse>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::RegisterResponse>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::RegisterResponse>>(PrepareAsyncRegisterRaw(context, request, cq));
    }
    // rpc Test(TestRequest) returns (TestResponse) {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::userinfo::SsoResponse>> Sso(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::userinfo::SsoResponse>>(SsoRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::userinfo::SsoResponse>> AsyncSso(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::userinfo::SsoResponse>>(AsyncSsoRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::userinfo::SsoResponse>> PrepareAsyncSso(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::userinfo::SsoResponse>>(PrepareAsyncSsoRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::LoginResponse>* AsyncLoginRaw(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::LoginResponse>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::RegisterResponse>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::RegisterResponse>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::userinfo::SsoResponse>* SsoRaw(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::userinfo::SsoResponse>* AsyncSsoRaw(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::userinfo::SsoResponse>* PrepareAsyncSsoRaw(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Login(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::userinfo::LoginResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::LoginResponse>> AsyncLogin(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::LoginResponse>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::LoginResponse>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::LoginResponse>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    ::grpc::Status Register(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::userinfo::RegisterResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::RegisterResponse>> AsyncRegister(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::RegisterResponse>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::RegisterResponse>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::RegisterResponse>>(PrepareAsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::userinfo::SsoResponse>> Sso(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::userinfo::SsoResponse>>(SsoRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::userinfo::SsoResponse>> AsyncSso(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::userinfo::SsoResponse>>(AsyncSsoRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::userinfo::SsoResponse>> PrepareAsyncSso(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::userinfo::SsoResponse>>(PrepareAsyncSsoRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::userinfo::LoginResponse>* AsyncLoginRaw(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::userinfo::LoginResponse>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::userinfo::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::userinfo::RegisterResponse>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::userinfo::RegisterResponse>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::userinfo::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::userinfo::SsoResponse>* SsoRaw(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request) override;
    ::grpc::ClientAsyncReader< ::userinfo::SsoResponse>* AsyncSsoRaw(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::userinfo::SsoResponse>* PrepareAsyncSsoRaw(::grpc::ClientContext* context, const ::userinfo::SsoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Login_;
    const ::grpc::internal::RpcMethod rpcmethod_Register_;
    const ::grpc::internal::RpcMethod rpcmethod_Sso_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Login(::grpc::ServerContext* context, const ::userinfo::LoginRequest* request, ::userinfo::LoginResponse* response);
    virtual ::grpc::Status Register(::grpc::ServerContext* context, const ::userinfo::RegisterRequest* request, ::userinfo::RegisterResponse* response);
    // rpc Test(TestRequest) returns (TestResponse) {}
    virtual ::grpc::Status Sso(::grpc::ServerContext* context, const ::userinfo::SsoRequest* request, ::grpc::ServerWriter< ::userinfo::SsoResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Login() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::userinfo::LoginRequest* request, ::userinfo::LoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::userinfo::LoginRequest* request, ::grpc::ServerAsyncResponseWriter< ::userinfo::LoginResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Register() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::userinfo::RegisterRequest* request, ::userinfo::RegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegister(::grpc::ServerContext* context, ::userinfo::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::userinfo::RegisterResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Sso : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Sso() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Sso() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sso(::grpc::ServerContext* context, const ::userinfo::SsoRequest* request, ::grpc::ServerWriter< ::userinfo::SsoResponse>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSso(::grpc::ServerContext* context, ::userinfo::SsoRequest* request, ::grpc::ServerAsyncWriter< ::userinfo::SsoResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Login<WithAsyncMethod_Register<WithAsyncMethod_Sso<Service > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Login() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::userinfo::LoginRequest* request, ::userinfo::LoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Register() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::userinfo::RegisterRequest* request, ::userinfo::RegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Sso : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Sso() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Sso() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sso(::grpc::ServerContext* context, const ::userinfo::SsoRequest* request, ::grpc::ServerWriter< ::userinfo::SsoResponse>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Login() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::userinfo::LoginRequest* request, ::userinfo::LoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Register() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::userinfo::RegisterRequest* request, ::userinfo::RegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegister(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Sso : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Sso() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Sso() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sso(::grpc::ServerContext* context, const ::userinfo::SsoRequest* request, ::grpc::ServerWriter< ::userinfo::SsoResponse>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSso(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Login() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::userinfo::LoginRequest, ::userinfo::LoginResponse>(std::bind(&WithStreamedUnaryMethod_Login<BaseClass>::StreamedLogin, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::userinfo::LoginRequest* request, ::userinfo::LoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::userinfo::LoginRequest,::userinfo::LoginResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Register() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::userinfo::RegisterRequest, ::userinfo::RegisterResponse>(std::bind(&WithStreamedUnaryMethod_Register<BaseClass>::StreamedRegister, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::userinfo::RegisterRequest* request, ::userinfo::RegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegister(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::userinfo::RegisterRequest,::userinfo::RegisterResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_Register<Service > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Sso : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_Sso() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler< ::userinfo::SsoRequest, ::userinfo::SsoResponse>(std::bind(&WithSplitStreamingMethod_Sso<BaseClass>::StreamedSso, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_Sso() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Sso(::grpc::ServerContext* context, const ::userinfo::SsoRequest* request, ::grpc::ServerWriter< ::userinfo::SsoResponse>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSso(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::userinfo::SsoRequest,::userinfo::SsoResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Sso<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_Register<WithSplitStreamingMethod_Sso<Service > > > StreamedService;
};

}  // namespace userinfo


#endif  // GRPC_user_5finfo_2eproto__INCLUDED
